evaluation_jobs:
  evaluation_1:
    config_body:
      type: AgentEvaluation
      agent_config_id: sharepoint_agent
      local_dataset: ""
      config_file_path: ""
      metric_config:
        relevance:
          name: "relevance"
          type: "BuiltInMetricsConfig"
          service:
            llm_service:  "AzureOpenAI"
            deployment_name: "gpt-4o"
        coherence:
          name: "coherence"
          type: "BuiltInMetricsConfig"
          service:
            llm_service:  "AzureOpenAI"
            deployment_name: "gpt-4o"
        intent_resolution:
          name: "intent_resolution"
          type: "AgentEvaluatorConfig"
          service:
            llm_service:  "AzureOpenAI"
            deployment_name: "gpt-4o"

