apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: {{KEYVAULTNAME}}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: KEYVAULT-URI
          objectType: secret
          objectVersion: ""
    tenantId: {{TENANTID}}