apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-provider
      containers:
        - name: ingestion-container
          image: craumj6cpfeztbo.azurecr.io/ingestion:${tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          resources:
            limits:
              cpu: "0.5"
              memory: "2Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
          - name: ENVIRONMENT
            value: "PROD"
      nodeSelector:
        agentpool: userpool

---

apiVersion: v1
kind: Service
metadata:
  name: ingestion
spec:
  ports:
  - port: 6001
    targetPort: 6001
  selector:
    app: ingestion
  type: ClusterIP