apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-manager
  template:
    metadata:
      labels:
        app: session-manager
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-provider
      containers:
        - name: session-manager-container
          image: craumj6cpfeztbo.azurecr.io/session-manager:${tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
          - name: ENVIRONMENT
            value: "PROD"
      nodeSelector:
        agentpool: userpool

---

apiVersion: v1
kind: Service
metadata:
  name: session-manager
spec:
  ports:
  - port: 5000
  selector:
    app: session-manager
  type: ClusterIP