# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from insights_generator.models.base_model_ import Model
from insights_generator import util


class CreateProjectRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self,
                 name: str = None,
                 product_category: str = None,
                 product_name: str = None):
        """CreateProjectRequest - a model defined in OpenAPI

        :param name: The name of this CreateProjectRequest.
        :param product_category: The product_category of this CreateProjectRequest.
        :param product_name: The product_name of this CreateProjectRequest.
        """
        self.openapi_types = {
            'name': str,
            'product_category': str,
            'product_name': str
        }

        self.attribute_map = {
            'name': 'name',
            'product_category': 'productCategory',
            'product_name': 'productName'
        }

        self._name = name
        self._product_category = product_category
        self._product_name = product_name

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CreateProjectRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The createProjectRequest of this CreateProjectRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CreateProjectRequest.


        :return: The name of this CreateProjectRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateProjectRequest.


        :param name: The name of this CreateProjectRequest.
        :type name: str
        """

        self._name = name

    @property
    def product_category(self):
        """Gets the product_category of this CreateProjectRequest.


        :return: The product_category of this CreateProjectRequest.
        :rtype: str
        """
        return self._product_category

    @product_category.setter
    def product_category(self, product_category):
        """Sets the product_category of this CreateProjectRequest.


        :param product_category: The product_category of this CreateProjectRequest.
        :type product_category: str
        """

        self._product_category = product_category

    @property
    def product_name(self):
        """Gets the product_name of this CreateProjectRequest.


        :return: The product_name of this CreateProjectRequest.
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name):
        """Sets the product_name of this CreateProjectRequest.


        :param product_name: The product_name of this CreateProjectRequest.
        :type product_name: str
        """

        self._product_name = product_name
