# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from insights_generator.models.base_model_ import Model
from insights_generator import util


class DataMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str = None, value: str = None):
        """DataMetadata - a model defined in OpenAPI

        :param name: The name of this DataMetadata.
        :param value: The value of this DataMetadata.
        """
        self.openapi_types = {'name': str, 'value': str}

        self.attribute_map = {'name': 'name', 'value': 'value'}

        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DataMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DataMetadata of this DataMetadata.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this DataMetadata.


        :return: The name of this DataMetadata.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DataMetadata.


        :param name: The name of this DataMetadata.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def value(self):
        """Gets the value of this DataMetadata.


        :return: The value of this DataMetadata.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DataMetadata.


        :param value: The value of this DataMetadata.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")

        self._value = value
