# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from insights_generator.models.base_model_ import Model
from insights_generator import util


class Summary(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text: str = None):
        """Summary - a model defined in OpenAPI

        :param text: The text of this Summary.
        """
        self.openapi_types = {'text': str}

        self.attribute_map = {'text': 'text'}

        self._text = text

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Summary':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Summary of this Summary.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self):
        """Gets the text of this Summary.


        :return: The text of this Summary.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Summary.


        :param text: The text of this Summary.
        :type text: str
        """

        self._text = text
