### Health Check
GET {{end-2-end-test-agent-url}}/e2etest

### Run Test Agent Manually
GET {{end-2-end-test-agent-url}}/e2etest/run

### Get All Scheduled Jobs
GET {{end-2-end-test-agent-url}}/e2etest/jobs

### Clear All Scheduled Jobs
POST {{end-2-end-test-agent-url}}/e2etest/jobs/clear

### Schedule a Job
POST {{end-2-end-test-agent-url}}/e2etest/jobs/schedule
Content-Type: application/json

{
  "hour": 10,
  "minute": 30,
  "second": 0,
  "timezone": "America/New_York"
}

### Stop Scheduler
POST {{end-2-end-test-agent-url}}/e2etest/jobs/stop