apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-provider 
      containers:
        - name: search-container
          image: craumj6cpfeztbo.azurecr.io/search:${tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 6002
          resources:
            limits:
              cpu: "0.5"
              memory: "2Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
          - name: ENVIRONMENT
            value: "PROD"
      nodeSelector:
        agentpool: userpool

---

apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
  - port: 6002
    targetPort: 6002
  selector:
    app: search
  type: ClusterIP