
###
# post a rag conversation
POST {{session_manager_url}}/chat?scenario=rag
Accept: application/json
Content-Type: application/json

{
    "user_id": "anonymous",
    "conversation_id": "pm_test_msg_01",
    "dialog_id": "dialog1",
    "message": {
        "payload": [
            {
                "type": "text",
                "value": "What was the revenue and what was the debt for IHC in the year 2023"
            }
        ]
    },
    "overrides":{
        "search_overrides": {
            "top": 200
        }
    }
}

###
# post a user conversation with overrides
POST {{session_manager_url}}/chat
Accept: application/json
Content-Type: application/json

{
    "user_id": "anonymous",
    "conversation_id": "test_search_config_101",
    "dialog_id": "dialog1",
    "message": {
        "payload": [
            {
                "type": "text",
                "value": "Who were the top 5 countries that imported the most in 2022 considering all goods categories and who are the top countries that imported the most 'Electrical machinery and electronic equipment' in the last 5 years?"
            }
        ]
    },
    "overrides":{
        "search_overrides": {
            "config_version": "demo-wto-tariff-profile-index_v3",
            "top": 1
        },
        "orchestrator_runtime": {
            "config_version": "trade_demo_citation_fix_v1"
        },
        "session_manager_runtime": {
        "config_version": "trade_demo_v1"
        }
    }
}

###
# get speech token

GET {{session_manager_url}}/get-speech-token

###
# get all user-profiles
GET {{session_manager_url}}/user-profiles

###
# get citation
GET {{session_manager_url}}/content/Trade_Map_List_of_supplying_markets_for_the_product_imported_by_United_States_of_America_2023-1.csv?override_version=trade_demo_v1