trigger:
  branches:
    include:
    - main
  paths:
    include:
    - MultiModalBot/src/config_hub
    - MultiModalBot/src/common

resources:
- repo: self

variables:
  namespace: 'default'

  # Image respository name
  imageRepository: 'confighub'

  # Project root folder.
  sourceRoot: $(System.DefaultWorkingDirectory)/MultiModalBot/src

  # Image describe root folder.
  configHubRoot: $(System.DefaultWorkingDirectory)/MultiModalBot/src/config_hub

  # Tag
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push Images
  jobs:  
  - job: Build
    displayName: Build Images
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build - Config Service
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(configHubRoot)/Dockerfile
        containerRegistry: $(DOCKER_REGISTRY_SERVICE_CONNECTION)
        buildContext: $(sourceRoot)
        tags: $(tag)

    - task: Docker@2
      displayName: Push - Config Service
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(DOCKER_REGISTRY_SERVICE_CONNECTION)
        tags: $(tag)

- stage: DevDeploy
  displayName: Dev - Deploy to Kubernetes
  dependsOn: BuildAndPush
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy to Kubernetes
    environment: $(ENVIRONMENT_NAME)
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Deploy Config Hub
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: $(K8S_SERVICE_CONNECTION)
              namespace: $(namespace)
              manifests: |
                $(configHubRoot)/k8s_manifest.yaml
              containers: |
                $(DOCKER_REGISTRY)/confighub:$(tag)