apiVersion: apps/v1
kind: Deployment
metadata:
  name: confighub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confighub
  template:
    metadata:
      labels:
        app: confighub
    spec:
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-secrets-provider 
      containers:
        - name: confighub-container
          image: cr5xd4xcq23ihzu.azurecr.io/confighub:${tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          resources:
            limits:
              cpu: "0.25"
              memory: "2Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      nodeSelector:
          agentpool: userpool
---
apiVersion: v1
kind: Service
metadata:
  name: confighub
spec:
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: confighub
  type: ClusterIP